const items = [
    {
        id: '001',
        image: '1.jpeg',
        company: 'Carlton London',
        item_name: 'Gold-Plated & Leaf design finish',
        original_price: 1045,
        current_price: 799,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '15 Aug 2024',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: '2.jpeg',
        company: 'FOSSIL',
        item_name: 'Fossil Brown & blue colored design ',
        original_price: 2599,
        current_price: 1584,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '15 Aug 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: '3.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red Printed With Knee-Length Skirts',
        original_price: 1599,
        current_price: 595,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '15 Aug 2024',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: '4.jpeg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket Jersey',
        original_price: 999,
        current_price: 899,
        discount_percentage: 8,
        return_period: 14,
        delivery_date: '15 Aug 2024',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: '5.jpeg',
        company: 'Roadster',
        item_name: 'Cotton T-shirt',
        original_price: 1399,
        current_price: 511,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '15 Aug 2024',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: '6.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 13999,
        discount_percentage: 6,
        return_period: 14,
        delivery_date: '15 Aug 2024',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: '7.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 480,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: '8.jpg',
        company: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        original_price: 285,
        current_price: 189,
        discount_percentage: 15,
        return_period: 14,
        delivery_date: '15 Aug 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];